# Generated by Django 5.1.6 on 2025-03-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqFOSj56PX7k71VGMxiVcwc8uXc3mLk78vyg&s', max_length=500),
        ),
    ]
